### ISSUE TITLE
Update README.md screenshot to use `mix gradient`

### ISSUE THREAD

**Issue by erszcz** [esl/gradient#1]

**Comment by Fl4m3Ph03n1x** [comment]
I am under the belief this was already done. 
Is there something you guys need help with ?

**Comment by erszcz** [comment]
It hasn't been done yet. The current screenshot from the README has the `mix gradualizer` invocation (not `mix gradient` as it is now) and doesn't sport the Elixir syntax for types in error messages (though it does in snippets quoted below the error messages). It would be awesome if you could grab a screenshot with the above take into account 🙏

**Comment by Fl4m3Ph03n1x** [comment]
![success](https://user-images.githubusercontent.com/2980392/155325195-724813d4-fb8d-4ed0-9fbd-948adb7249f9.png)
![error](https://user-images.githubusercontent.com/2980392/155325205-6eb3e43f-6b6a-4a42-84ea-edd55ef368ff.png)

I couple of screenshots here. I thought about making a gif but I am not sure it makes sense to be honest. 
Let me know if these are good enough.

**Comment by Premwoik** [comment]
For me, these screenshots are enough and look good. But you can make a gif if you want :)

**Comment by Fl4m3Ph03n1x** [comment]
Are there any special commands or flags I can use to showcase ?

**Comment by Premwoik** [comment]
Currently, we don't support any. There is task #3 about adding them.

**Comment by Fl4m3Ph03n1x** [comment]
Should I make a PR with the updated screenshots ? (that I presented in this thread)

**Comment by erszcz** [comment]
@Fl4m3Ph03n1x Yes, please create a PR - that would be awesome! One thing to note - could you make sure there's a space between the `$` and the command (likely missing in your `PS1` env var if that's bash)?

```
~/simple_app$mix gradient
```

vs

```
~/simple_app$ mix gradient
```

It looks a bit strange without the space :)

**Comment by Fl4m3Ph03n1x** [comment]
I finally got the time and made a PR for this issue:
https://github.com/esl/gradient/pull/58

Please let me know what you guys think.

**Comment by erszcz** [comment]
Thanks, @Fl4m3Ph03n1x!
