### ISSUE TITLE
Multiple modules in single file are not loaded into gradualizer_db

### ISSUE THREAD

**Issue by luk-pau-es** [esl/gradient#125]
In Elixir there is possibility that multiple modules are present in the same file. This poses a problem because not all data for modules is loaded into gradualizer_db. Using functions such as `code.load_binary/3` will only allow elixir/erlang to upload file into VM memory but not in gradualizer

Minimal code example to reproduce, both modules in same files:
```elixir
defmodule TypeDef do
  @type t() :: integer()
end

defmodule FunDef do
  @spec f() :: TypeDef.t()
  def f(), do: 1
end
```

When we call `mix gradient` or `gradient` escript we get result:
```
test/examples/dependent_modules.ex: Undefined remote type TypeDef.t/0 on line 6
Total errors: 1
``` 

Expected behaviour: No errors found

**Comment by erszcz** [comment]
This should already be taken care of in #121.
