### ISSUE TITLE
EScript: print help instead of running analysis by default

### ISSUE THREAD

**Issue by erszcz** [esl/gradient#152]
Running the escript with no CLI params, i.e. `gradient` or `gradient --help`, should just print the usage help, not run the analysis on the current working directory.

**Comment by luk-pau-es** [comment]
To specify possible scenarios:
1. `gradient` - print help
2. `gradient --help` - print help
3. `gradient path/to/file` - run analysis
4. `gradient --help path/to/file` - print help or run analysis or both?

In my opinion in each situation where we have `--help` flag we should only print help. @erszcz what do you think?
