### ISSUE TITLE
Failure when matching on one specific return

### ISSUE THREAD

**Issue by rodrigues** [esl/gradient#24]
If a function can return more than one type, and I match on one specific type, the check fails.

I'm not sure if this is intended behaviour, but raising here as an issue, thinking this usage should not raise any failures?

Cheers!

```elixir
defmodule Gradissue do
  @spec foo(integer()) :: :ok
  def foo(x) do
    :ok = bar(x)
  end

  @spec bar(integer()) :: :ok | {:error, term()}
  defp bar(0), do: :ok
  defp bar(x), do: {:error, x}
end
```

```shell
❯ mix gradient
Compiling 1 file (.ex)
Typechecking files...
lib/gradissue.ex: The function call on line 4 is expected to have type :ok but it has type :ok | {:error, term()}
2   @spec foo(integer()) :: :ok
3   def foo(x) do
4     :ok = bar(x)
5   end
6 

```

**Comment by erszcz** [comment]
Thanks, Victor!

In this case the warning is valid, since `bar` spec is explicit about the possible return values, but one of them is ignored. This makes the program unsound. If the other type gets returned we'll get a runtime crash, and the type system's purpose is exactly that - to prevent runtime crashes.

If you really want to convert from an error-as-value to an exception, it has to be explicit:

```elixir
defmodule Gradissue do
  @spec foo(integer()) :: :ok
  def foo(x) do
    case bar(x) do
      :ok ->
        :ok
      {:error, reason} ->
        ## given FooError is defined
        raise FooError, reason: reason
        ## or maybe just:
        ## :erlang.error(reason)
  end

  @spec bar(integer()) :: :ok | {:error, term()}
  defp bar(0), do: :ok
  defp bar(x), do: {:error, x}
end
```

**Comment by rodrigues** [comment]
Ahh got it, I thought matching on a subset and crashing otherwise was ok, so that's fine then. If that could be a flag haha, that would be great, but I guess that depends more on gradualizer than gradient itself?

Something I've noticed though is that using `case`, it's not making sure I'm considering all the paths:

```elixir
defmodule Gradissue do
  @spec foo(integer()) :: :ok
  def foo(x) do
    case bar(x) do
      :ok ->
        :ok

      {:error, _} ->
         :ok
    end
  end

  @spec bar(integer()) :: :ok | {:error, term()} | {:wupwup, term()}
  defp bar(0), do: :ok
  defp bar(x) when x < 0, do: {:error, x}
  defp bar(x), do: {:wupwup, x}
end
```

```shell
❯ mix gradient
Compiling 1 file (.ex)
Typechecking files...
No problems found!
```

It passes even if I remove the `{:error, _} ->` clause.

**Comment by erszcz** [comment]
Ahhh, that's interesting 🤔 What happens if you check with this instead?

```elixir
  @spec bar(integer()) :: :ok | {:error, integer()} | {:wupwup, integer()}
```

**Comment by erszcz** [comment]
Indeed, it's what I expected. With:

```elixir
$ cat lib/gradissue.ex
defmodule Gradissue do
  @spec foo(integer()) :: :ok
  def foo(x) do
    case bar(x) do
      :ok ->
        :ok

      {:error, _} ->
         :ok
    end
  end

  @spec bar(integer()) :: :ok | {:error, integer()} | {:wupwup, integer()}
  defp bar(0), do: :ok
  defp bar(x) when x < 0, do: {:error, x}
  defp bar(x), do: {:wupwup, x}
end
```

We get:

```
$ mix gradient
Compiling 1 file (.ex)
Typechecking files...
lib/gradissue.ex: Nonexhaustive patterns on line 5
Example values which are not covered:
	{wupwup, 0}
```

The thing is that `term()` (and `any()` which is a synonym to `term()`) is the _unknown type_ in the gradual type system. It means it's compatible with anything, which in turn means it cannot be used for exhaustiveness checking - that is figuring out whether you missed a branch or not.

In other words, if we want to rely on `Nonexhaustive patterns ...` warnings, our type variants cannot use `term()` or `any()`.

**Comment by erszcz** [comment]
@rodrigues I hope this is a convincing answer :) Let me know if that's not the case :D Until then, I'll close this one.
