### ISSUE TITLE
Double quote atoms when printing

### ISSUE THREAD

**Issue by erszcz** [esl/gradient#34]
As found out by @eksperimental in #30 some atoms are printed incorrectly, i.e. after printing they're not parseable as atoms anymore:

> Some atoms need double quotes, such as :1.13.0 they should be represented as :"1.13.0"

We have to take care to double quote them as appropriate.

**Comment by eksperimental** [comment]
Here's the reference for atom formatting:
https://hexdocs.pm/elixir/syntax-reference.html#atoms

If you are going to format the output with the Elixir formatter you can always use double quotes and let the formatter take care of the rest.

**Comment by Premwoik** [comment]
Because we merged #43, I think we can close this.
