### ISSUE TITLE
The pattern %{moves: []} on line 39 doesn't have the type any()

### ISSUE THREAD

**Issue by dkuku** [esl/gradient#51]
Hi. thanks for working on gradient. 
Error I'm getting when running gradient without any specs on function definition with pattern matching.
Some examples:
`def play(%{moves: []} = game, _move, _roll) do`
`def play(%{moves: [{_round, player} | new_moves]} = game, move, roll) do`
adding spec definitions makes them go away but the initial run looks scary and does not suggest a proper solution

**Comment by erszcz** [comment]
Thanks for the report, @dkuku!

Indeed, in the light of no spec this warning should not be produced - it's a known bug. It's also mentioned in #37 as one of the issues. I checked if it's specific to Gradient or also present in Gradualizer and it's the latter - there's already josefs/Gradualizer#387 to track it upstream.
