### ISSUE TITLE
Multiple specs are allowed per function, but Gradient says they can't.

### ISSUE THREAD

**Issue by eksperimental** [esl/gradient#74]
I have the following specs
```
  @spec child_pid(arg) :: arg when arg: pid
  @spec child_pid(name) :: pid
```

And I get this error:

`lib/checker.ex: The spec child_pid/1 on line 126 follows another spec, but only one spec per function clause is allowed`

**Comment by Premwoik** [comment]
Hi! Currently, the allowed `@spec` position is described in the comment:
https://github.com/esl/gradient/pull/55#issue-1153802075

The goal behind implementing this `spec check` was to warn when the spec is accidentally placed above another function:
```elixir
@spec a() :: binary()
def b(atom) when is_atom(atom), do: to_string(atom)
```

We are open to suggestions on the acceptable spec locations :)

**Comment by Premwoik** [comment]
Ok, you are right. We need to correct it :)

**Comment by eksperimental** [comment]
Awesome

**Comment by eksperimental** [comment]
Thank you @Premwoik
