### ISSUE TITLE
"Call to undefined function" error, when the remote function exists

### ISSUE THREAD

**Issue by eksperimental** [esl/gradient#75]
Getting:
```
lib/checker.ex: Call to undefined function Checker.Util.child_pid/1 on line 128
lib/checker.ex: Call to undefined function Checker.Util.child_pid/1 on line 136
```

You can see this repo at this specific commit to replicate the error
https://github.com/eksperimental/checker_basic/tree/bd2bcbe717863c4a1c0c7acc1866072815608e52

Also getting:
```
lib/checker/mock.ex: Undefined remote type Checker.url/0 on line 15
```
when the type does exist.

**Comment by Premwoik** [comment]
Thanks for reporting :) I will investigate it. Seems that modules are not loaded to the Gradualizer.

**Comment by eksperimental** [comment]
Thank you for the fix @Premwoik
