### ISSUE TITLE
Error with `integer` type passed to `Process.sleep`

### ISSUE THREAD

**Issue by baldwindavid** [esl/gradient#83]
I'm testing out gradient on a https://github.com/baldwindavid/ex_waiter/pull/3 and running into a case where I have function that should return an `integer`. However, Gradient returns an error because this value is being passed to `Process.sleep`. Gradient seems to think this value must be a `timeout` rather than `integer` if I'm understanding correctly. Here is a link to the function with the desired `@spec` commented out...
https://github.com/baldwindavid/ex_waiter/pull/3/files#diff-a502442c0bd637c012b9c3bd3788d431af95331497257e34e1a53bb8a5446f49R325

**Comment by erszcz** [comment]
Hey, @baldwindavid!

Thanks for your interest in Gradient! This is a valid warning - [according to the docs `timeout()` is](https://hexdocs.pm/elixir/1.12/typespecs.html#built-in-types):

```elixir
@type timeout() :: :infinity | non_neg_integer()
```

Which means not every `integer()` is a valid `timeout()` - specifically a timeout cannot be negative, but it can be `:infinity`. Let's check `Process.sleep()` docs:

```elixir
iex(4)> h Process.sleep

  @spec sleep(timeout()) :: :ok
```

Let's check one more thing:

```elixir
iex(6)> Process.sleep(-5)
** (FunctionClauseError) no function clause matching in Process.sleep/1

    The following arguments were given to Process.sleep/1:

        # 1
        -5

    Attempted function clauses (showing 1 out of 1):

        def (sleep(timeout) when is_integer(timeout) and timeout >= 0) when timeout == :infinity

    (elixir 1.12.2) lib/process.ex:250: Process.sleep/1
```

All in all, Gradient is right. It points out an inconsistency in the values that are passed between those functions, which, as can be seen in the last snippet, can lead to a runtime crash. And that's exactly what Gradient is supposed to catch :+1:

**Comment by baldwindavid** [comment]
Ah, of course. Love it and sorry for the noise.
