### ISSUE TITLE
Show line number next to the file name

### ISSUE THREAD

**Issue by Defman21** [esl/gradient#86]
As for now, the line number is in the error message. Making it `$pathToFileName:$lineNo` (e.g., `lib/myproject/myfile.ex:10`) would make it easier to jump to the line from editors that support that kind of stuff (e.g., VS Code does support it if it's in the terminal output).

**Comment by erszcz** [comment]
Good point, thanks for the suggestion :+1:
This format is already available in Gradualizer itself, so indeed, we should also make it possible in Gradient.

**Comment by erszcz** [comment]
> it appears that when you pass `--fmt-location brief`, it does output the line number next to the file name.

It's the same as Gradualizer, then, and I think that's fine. It's a matter of configuring the editor/IDE to pass the flag.

**Comment by Defman21** [comment]
Yeah, that's what I meant. I just didn't know this option exists.

**Comment by erszcz** [comment]
No worries. Thanks for raising anyway, I was not sure if we're compatible with Gradualizer with regard to this option already.
