### ISSUE TITLE
Gradient does not deal with function heads with default args

### ISSUE THREAD

**Issue by eksperimental** [esl/gradient#88]
```elixir
defmodule DefaultArgs do
  @spec foo(term, term) :: {term, term}
  def foo(arg1, arg2 \\ nil)

  def foo(arg1, arg2) do
    {arg1, arg2}
  end
end
```

will generate:

> lib/debug_gradient/defaul_args.ex: The spec foo/2 on line 2 doesn't match the function name/arity

**Comment by erszcz** [comment]
Hmmm, @Premwoik, this seems like another case we need to handle in the Elixir spec placement rule. I'm not sure how to detect such cases, though 🤔

**Comment by eksperimental** [comment]
Yes, it works! Thank you @erszcz
