### ISSUE TITLE
Typespec support documentation

### ISSUE THREAD

**Issue by baldwindavid** [esl/gradient#92]
It's nice to see projects like Gradient, TypeCheck, and Norm developing to improve the ability to check types in Elixir. Fairly early on in the development of TypeCheck I added a page that broke down the current status of support for the typespecs. This is mostly just Elixir's typespec documentation with checkmarks next to what is/isn't supported. At this point, most of it is supported in some way:
https://hexdocs.pm/type_check/comparing-typecheck-and-elixir-typespecs.html

Would it be useful to have something similar for this project? I am excited about both projects, but they go at the problem in completely different ways. Perhaps it also be helpful to compare and contrast the projects at some point.

**Comment by erszcz** [comment]
That might be quite an effort, though, so it's completely understandable if you cannot afford the time.

Another perspective at feature completeness is consideration of what language constructs are already covered by the type checker. Alas, neither Gradient nor Gradualizer have such documentation available so far - the only documentation (of this aspect) is the implementation. Recently we had some issues touching this aspect such as #85, #73, or #84 that you raised.

**Comment by baldwindavid** [comment]
Cool, if I get a chance, I may take a crack at it. I'm still very much a noob of gradient/gradualizer so it probably wouldn't be imminent. I do know that the TypeCheck creator will also be talking soon about some of the tradeoffs between TypeCheck, Gradualizer, and Dialyzer... https://www.elixirconf.eu/talks/typecheck-effortless-runtime-type-checking/ - Maybe that helps inform some of the documentation.
